#!/usr/bin/env node

// Redacts all files passed on command line in place.

import { readFileSync, writeFileSync } from "node:fs";
import redact from "../cli/lib/redact.js";

const [, , ...paths] = process.argv;

for (const path of paths) {
  console.log(`Redacting ${path}`);
  writeFileSync(path, redact(readFileSync(path, "utf8")));
}
