name: Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install actionlint
        working-directory: ${{ runner.temp }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Download and install actionlint
          set -euo pipefail

          mkdir actionlint
          cd actionlint
          gh release download \
            --repo rhysd/actionlint \
            --pattern 'actionlint_*_linux_amd64.tar.gz'
          gh attestation verify actionlint_*.tar.gz \
            --repo rhysd/actionlint

          tar xzf actionlint_*.tar.gz
          cp actionlint /usr/local/bin
      - name: Install ghalint
        working-directory: ${{ runner.temp }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Download and install ghalint
          set -euo pipefail

          mkdir ghalint
          cd ghalint
          gh release download \
            -R suzuki-shunsuke/ghalint \
            -p 'ghalint_*_linux_amd64.tar.gz'
          gh attestation verify ghalint_*.tar.gz \
            -R suzuki-shunsuke/ghalint \
            --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml

          tar xzf ghalint_*.tar.gz
          cp ghalint /usr/local/bin
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          extra-args: --all-files --skip typos --skip zizmor

  typos:
    name: typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: crate-ci/typos@bbaefadf97b0ec5fdc942684b647f1a6ab250274 # v1.46.0

  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      security-events: write # reporting lint failures
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          inputs: .
          persona: pedantic
